<template>
	<progress
	:class="['onekit-progress',onekitClass]"
	:style="onekitStyle"
	:percent="percent"
	:show-info="showInfo"
	:border-radius="borderadius"
	:font-size="fontize"
	:stroke-width="strokeWidth"
	:activeColor="activeColor"
	:backgroundColor="backgroundColor"
	:color="color"
	:active="active"
	:active-mode="activeMode"
	:duration="duration"
	@activeend="progress_activeend"/>
</template>

<script>
	export default{
		props:{
			onekitClass:{
				type:String,
				default:''
			},
			onekitStyle:{
				type:String,
				defaul:''
			},
			percent:{
				type:String,
			},
			showInfo:{
				type:Boolean,
				default:false
			},
			borderadius:{
				type:String,
				default:'0'
			},
			fontize:{
				type:String,
				default:'16'
			},
			strokeWidth:{
				type:String,
				default:'6'
			},
			color:{
				type:String,
				default:'#09BB07'
			},
			activeColor:{
				type:String,
				default:'#09BB07'
			},
			backgroundColor:{
				type:String,
				default:'#EBEBEB'
			},
			active:{
				type:Boolean,
				default:false
			},
			activeMode:{
				type:String,
				default:"backwards"
			},
			duration:{
				type:Number,
				default:30
			}
		},
		data(){
			return{}
		},
		created:function(e){
			if(this.$props.color){
				var color = this.$props.color;
				this.$props.activeColor = color;
			}
		},
		methods:{
			progress_activeend:function(e){
				this.$emit('activeend',e)
			}
		}
	}
</script>

<style>
</style>
